### ISSUE TITLE
Support blockwise transfer

### ISSUE THREAD

**Issue by ShadowJonathan** [martindisch/coap-lite#16]
Title, we require this for https://github.com/ruma/lb/issues/3, RFC for this is [here](https://datatracker.ietf.org/doc/html/rfc7959)

**Comment by martindisch** [comment]
I haven't planned on adding it, but it looks like a neat project you're working on. If you manage to pull it off in your fork and would like to upstream it later on, feel free to let me know.

**Comment by ShadowJonathan** [comment]
This is definitely something we'll upstream once we got it working 👍

**Comment by martindisch** [comment]
In the meantime somebody went ahead and implemented RFC7959, you can check it out in #21. I'm assuming you have already solved your particular problem anyway, so I'm closing this.
