### ISSUE TITLE
CoAP packet size is limited to 1280

### ISSUE THREAD

**Issue by digitwolf** [martindisch/coap-lite#25]
There is a hardcoded limit for the coap payload size. 
https://github.com/martindisch/coap-lite/blob/dabbf906e0c9693d43801b205679f1be25e543d4/src/packet.rs#L694

Any concerns if we make it configurable?
If not, would you have any preference in how to implement it?

I was thinking of adding a feature flag. By default keep the current value. Add a feature for UDP payload size. 

Coap RFC on size 
https://datatracker.ietf.org/doc/html/rfc7252#page-25

**Comment by martindisch** [comment]
That seems reasonable, feel free to make a suggestion PR with the feature.

Note: it might take a day or two to get it merged, it's a bit busy at the moment.
