### ISSUE TITLE
More examples is needed.

### ISSUE THREAD

**Issue by Tnze** [martindisch/coap-lite#27]
The current example client code in the README doesn't receive the response and doesn't process the Block-Wise Transfers.

**Comment by martindisch** [comment]
True, the current ones are rather simplistic and just a kind of quickstart guide. If you have any good examples of how you're using this functionality, I'd be happy to add them.

**Comment by Tnze** [comment]
I found a big example of how to use this crate: [the `coap` crate](https://crates.io/crates/coap).
![ZFA~}(EE%(@GRRO0Z_%HSUJ](https://user-images.githubusercontent.com/19628575/184631164-566042d4-e1e1-485e-a6f2-69295f89cbc6.jpg)

**Comment by martindisch** [comment]
That's great! Since this is a pretty low-level library and most people should be using `coap` that's built on top of it anyway, I think that's the perfect place to go look.
