### ISSUE TITLE
No_std support lost due to lru_time_cache dependency?

### ISSUE THREAD

**Issue by dkhayes117** [martindisch/coap-lite#29]
Hi, I was looking into using your library in a no_std environment, but I am unable to compile due to lru_time_cache dependency which seems to need std.  Even with setting default-features to false, the project will not build.
```
coap-lite = { version = "0.11.1", default-features = false }
```
```
   Compiling lru_time_cache v0.11.11
error[E0463]: can't find crate for `std`
```

**Comment by martindisch** [comment]
Thanks for pointing this out, that was an oversight on my part. I moved the dependency and the feature that requires it behind the `std` feature in #30. Please try again with version 0.11.2.

**Comment by dkhayes117** [comment]
Yep that fixed it, appreciate the quick response and fix!
