### ISSUE TITLE
ObserveOption doesn't support sequence numbers

### ISSUE THREAD

**Issue by jiayihu** [martindisch/coap-lite#3]
The current implementation is actually wrong because the RFC 7641 states that it's also used to send the message sequence, so 0/1 are not the only allowed values. There was already an error from the the previous impl because if the value is 0 (Register), it should actually be omitted but this has been fixed in #2 

> When included in a response, the Observe Option identifies the message as a notification. This implies that a matching entry exists in the list of observers and that the server will notify the client of changes to the resource state. The option value is a sequence number for reordering detection (see Sections 3.4 and 4.4).

https://github.com/martindisch/coap-lite/blob/2082b6ad61b58f928abc804282570148d09b7b2f/src/packet.rs#L173-L198

It's not a big issue since one can workaround by directly reading and writing the option without using the enum. `Packet::set_observe` takes a generic `Vec<u8>`. It's also not a big issue for embedded devices which usually send the data, it's the receiver which must correctly check the sequence number for ordering.

I don't have the time to fix it now so I'll just leave the issue open for information

**Comment by martindisch** [comment]
Good catch! I don't have time to look into it either, but it's useful to have it documented here.

**Comment by jasta** [comment]
This should now be fixed with #19.

**Comment by martindisch** [comment]
Missed that, thanks for the reminder.
