### ISSUE TITLE
message size limit

### ISSUE THREAD

**Issue by koalatux** [martindisch/coap-lite#34]
coap-lite currently implements two different message size limits. 1280 bytes or 64000 bytes with the "udp" feature.

1280 Bytes is the minimum IP MTU which must be supported by an IPv6 link. Within these 1280 bytes you also have to accommodate space for the IP and UDP headers, which leaves less than 1280 bytes space for the CoAP message. RFC 7252 recommends to use 1152 bytes for the maximum CoAP message size if nothing about the lower layers is known, which is 128 bytes fewer than coap-lite currently implements.

coap-lite limits the message size to near the minimum supported IP MTU. As a user I would like to use a different message size limit if the MTU is known beforehand or if an application performed a path MTU discovery at runtime.

For the "udp" feature case, the theoretical maximum size of UDP over IPv4 is 65535 bytes, subtracting IPv4 and UDP header sizes from that results in 65507 bytes, which is 1507 bytes more than coap-lite implements in this case. While such large IP packets are possible, they will most surely be fragmented, which is not recommended for CoAP. (For IPv6 with the jumbo payload option, theoretical packet sizes of up to 4 GiB are possible.)

I suggest to make the message size check optional and/or make it configurable with a custom limit, or remove it at all.

**Comment by martindisch** [comment]
That seems reasonable, though I'll have to think about what the nicest option would be.

- A feature to disable it completely would be mutually exclusive with the `udp` feature, I wonder how to best model this
- Making it configurable would likely mean adding the option to the runtime API surface, which could be clunky

**Comment by koalatux** [comment]
As far I've seen the limit is only applied in `Packet::to_bytes(&self)`. Without a breaking change you could for example add two new methods `Packet::to_bytes_with_limit(&self, n: usize)` and `Packet::to_bytes_unlimited(&self)`.

**Comment by martindisch** [comment]
If that suits your needs, I'm happy to do it. Will look into it tomorrow. By the way, I'm always curious what type of projects people use the library for, if you can share any details.

**Comment by koalatux** [comment]
Thanks for your reply. For my purpose the unlimited case would be enough, I can do the check if it fits after I converted the packet to bytes. The other case might be an optimization on a more constrained device in order to not having to allocate memory in the first place if it doesn't fit.

As a background: We have kind of a proxy that allows an IoT device which is connected via CoAP to a gateway to open TCP and/or TLS connections from that Gateway to the Internet. We initially have written it in Python using aiocoap and then ported it to Rust. There was a discussion with more details about the protocol in aiocoap's issue tracker: https://github.com/chrysn/aiocoap/issues/281

**Comment by martindisch** [comment]
Took me a while to get to it, but finally released the change in 0.11.5. Take a look and see if it works for you.

> As a background: We have kind of a proxy that allows an IoT device which is connected via CoAP to a gateway to open TCP and/or TLS connections from that Gateway to the Internet.

Cool! Is that by any chance related to gardening considering your work? It's great to see more Rust adoption in real appliances!

**Comment by koalatux** [comment]
Thanks a lot, that looks good to me.

Yes, it will be a service running on our [smart garden Gateway](https://github.com/husqvarnagroup/smart-garden-gateway-public). We are trying to use Rust more and more, [here](https://github.com/husqvarnagroup/smart-garden-gateway-yocto-meta-gardena/tree/e23267c1b5bafbc54bd8c51cb86e73b6a2b816be/recipes-support/overlayfs-purge/overlayfs-purge) is another tool we wrote in Rust and released to the public a while ago.
