### ISSUE TITLE
Copying request payload to the reply

### ISSUE THREAD

**Issue by amvasil-v** [martindisch/coap-lite#37]
``While testing [coap-rs](https://github.com/Covertness/coap-rs), which is based on coap-lite, I noticed that coap server by default replies to the POST and PUT requests with an echo of the request, which is confusing. Moreover, it copies request payload to the reply messages to a block1 request, which is clearly a bug.

This happens because in `src/response.rs` in the function `pub fn new(request: &Packet)`:
`packet.payload = request.payload.clone();`
request payload is always copied to the reply.

Is there a particular reason to do it, or can this line be deleted? I think in all use cases user is actually responsible for populating `response.message.payload`.

**Comment by martindisch** [comment]
I'm not sure, this behavior has been here from the beginning in #1. @Covertness do you remember the reasoning by chance, or have a preference on the matter?

**Comment by Covertness** [comment]
I think it was used to build the response quickly. Of cource it can be deleted.

**Comment by amvasil-v** [comment]
@martindisch @Covertness Thanks for a quick reply! Created PR #38.

**Comment by martindisch** [comment]
Released in 0.12.0.
