### ISSUE TITLE
Derive PartialEq for structs

### ISSUE THREAD

**Issue by ghost** [martindisch/coap-lite#41]
During my development I encountered the need to compare several pub structs:
- CoapRequest
- CoapResponse
- Packet
- Header

It will be nice if you can derive PartialEq for them in order to simplify the usage of your library (and save the need to write these comparisons manually).

Thanks in advance

**Comment by martindisch** [comment]
Done and published in 0.13.0 together with the other change. In the future please consider creating pull requests yourself, especially for simple requests like this.
