### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by jiayihu** [martindisch/coap-lite#5]
Now that coap-rs uses this crate under the hood, I think we could improve the description in the README. I think we should emphasise more on describing it as a low-level CoAP implementation, but no **that much** low-level that it's useful only for embedded/no-std as one might think.

Also we can use some better example than showing how to format to and parse from binary, e.g. using higher-level `CoapRequest` and `CoapRequest`. Also pointing to coap-rs as real-world example of usage.

**Comment by jiayihu** [comment]
With #4 we should also promote which RFCs are supported

**Comment by martindisch** [comment]
That's a good idea, if you go for it I'm happy to take a look. The only thing you need to know is that I want to keep the crate-level documentation (in `lib.rs`) and the README in sync, to prevent duplicating stuff.

The way it works is we only make changes in `lib.rs` and then run `cargo sync-readme` (you may need to first install it with `cargo install cargo-sync-readme`) to copy the changes to the actual README file.

**Comment by jiayihu** [comment]
Cool thanks for the info. Now I only need to find the time for it 😄
